# Generated by Django 5.0 on 2024-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="duration_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="duration_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
